version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: nestjs-bp-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - database:/data/postgres
    ports:
      - '5431:5432'
volumes:
  database: