version: '3.8'

services:
  database:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: nestjs-bp-mongo
    restart: always
    env_file:
      - .env
    volumes:
      - database:/data/mongodb
    ports:
      - '27017:27017'
volumes:
  database: